### ISSUE TITLE
Practica TestRail

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-team-remi#1]
[Práctica #2 - Unidad 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-team-remi/files/9678706/Practica.2.-.Unidad.2.pdf)

**Comment by bg55-a** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
